DRAFT: Explicit cancellation of streams on client exceptions
well-typed/grapesy pull request #211
Opened 2024-08-23 17:21 UTC by FinleyMcIlwaine

Currently a draft/test PR

2024-08-29 15:06 UTC, edsko commented
We need to make that when we merge this, we close #209 and consider all mentions of #209 in the code (including the new mention added in #210).

2024-09-03 08:53 UTC, edsko requested changes

2024-09-03 08:53 UTC, edsko commented on test-grapesy/Test/Sanity/Exception.hs
> +        -- This is never hit, since our client never sends 'NoMoreElems'.
This should ideally be an `error` call then?

2024-09-03 08:53 UTC, edsko commented on interop/Interop/Client/TestCase/CancelAfterBegin.hs
> -          return ()
This change is not conform the spec, I think (see the interop test referenced in the test description). Let's discuss.

2024-09-04 22:51 UTC, FinleyMcIlwaine commented
I believe this is ready for merge.

As far as the `writeChunkFinal` goes in the `NoMoreElems` case of `sendMessageLoop`, I was able trigger a `RST_STREAM` frame when it was removed and there were appropriate `threadDelay`s in place. It's difficult to add a test detecting that behavior, since it's very race-y on the `http2` side (the `finished` *almost* always beats the `outBodyCancel` resulting from the `cancelRequest` in grapesy, so we need that `threadDelay` in the `finished` to reliably trigger it)

2024-09-05 14:28 UTC, edsko approved these changes
Such a relief to get this in!

2024-09-05 14:28 UTC, merged