Add Snappy compression
well-typed/grapesy pull request #87
Opened 2024-02-12 22:53 UTC by FinleyMcIlwaine

* `snappy` is now a supported encoding, via the [snappy-c](https://hackage.haskell.org/package/snappy-c) library.
* Add a `snappy` test to the `Test.Sanity.StreamingType.NonStreaming.compression` group.

Resolves #56

2024-02-13 10:15 UTC, edsko commented
I would prefer not disable 8.10.7 altogether for grapesy. Can we set things up so that we configure CI to disable snappy support for ghc < 9.2 instead?

2024-02-13 13:38 UTC, edsko requested changes
Can we set things up so that we still test grapesy for ghc < 9.2, but just disable snappy in that case?

2024-02-13 19:51 UTC, FinleyMcIlwaine commented
I've re-enabled 8.10.7 support, and made a revision on hackage to support 8.10.7 in snappy-c, so we can test snappy on all versions. The only issue is that snappy-c requires bytestring >= 0.11, which is greater than the version bundled with 8.10.7. So the default haskell-ci behavior of adding `constraint: pkg installed` for each boot package `pkg` leads to resolution failures on 8.10.7. The best way I've found to address this is adding `installed: -all` to the haskell-ci configuration. Let me know how that looks to you!

2024-02-21 12:34 UTC, edsko commented
The dependency on `bytestring` seems unproblematic. I've rebased this branch and have changed the `snappy` flag to be automatic and default to true; for full compliance, this seems the better default.

2024-02-21 12:38 UTC, edsko approved these changes

2024-02-21 12:38 UTC, merged